### ISSUE TITLE
[BUG] The textures of the underground storages are broken

### ISSUE THREAD

**Issue by VladislavPrimakov** [nicolas-lang/Factorio.LongStorageTanks#8] opened 2024-02-21 19:54 UTC
The texture of the underground pipes is broken and looks ugly, can you fix it?
![image](https://github.com/nicolas-lang/Factorio.LongStorageTanks/assets/61202829/da79ee60-bdfe-4f7e-9a77-54e408e15047)

**Comment by nicolas-lang** [comment] 2024-02-21 19:56
Are you playing on low resolution by chance? I thing I never got the scaling right for low-res and forgut about it since i play mostly hr...

**Comment by VladyslavPrymakov** [comment] 2024-02-21 19:58
![image](https://github.com/nicolas-lang/Factorio.LongStorageTanks/assets/61202829/11c6928c-09d3-4ec9-8521-a84b5b3b43ef)
I haven’t logged into the game for a couple of months and decided to update both the mods and the factorio itself. It looked fine before

**Comment by nicolas-lang** [comment] 2024-02-21 20:00
"I haven’t logged into the game for a couple of months..."
... same here, I'll see when I can spare some time to install factorio again and have a look, not sure if I manage to do it this weekend

**Comment by VladyslavPrymakov** [comment] 2024-02-21 20:06
![image](https://github.com/nicolas-lang/Factorio.LongStorageTanks/assets/61202829/15e5499e-a6ea-4060-95eb-971e14b44524)
It would be great if I could add pumps to the outlets from the tanks in the facility itself so that I wouldn’t have to install these pumps myself.

**Comment by nicolas-lang** [comment] 2024-11-17 19:25
duplicate of https://github.com/nicolas-lang/Factorio.LongStorageTanks/issues/1
shoudl be fixed for factorio 2.0
please re-open if issue persists with 2.0

**Closed by nicolas-lang** 2024-11-17 19:25 UTC
